// NEXUS — Core Domain Specifications & Types

export type AgentRole =
  | 'GAME_DIRECTOR'
  | 'DISCOVERY_AGENT'
  | 'WORLD_ARCHITECT'
  | 'STORY_NARRATIVE'
  | 'CHARACTER_DESIGNER'
  | 'GAMEPLAY_DESIGNER'
  | 'CINEMATOGRAPHY'
  | 'PHYSICS_SIMULATION'
  | 'AUDIO_DIRECTOR'
  | 'GAME_BUILDER'
  | 'QA_TESTER'
  | 'PERFORMANCE_OPTIMIZER';

export interface AgentTaskStatus {
  agentRole: AgentRole;
  status: 'idle' | 'running' | 'completed' | 'failed';
  summary: string;
  details?: Record<string, unknown>;
  timestamp: string;
}

// Fictional Universe Specification
export interface UniverseLocation {
  id: string;
  name: string;
  type: string; // e.g. "Orbit Station", "Glacial Crater", "Ancient Temple"
  description: string;
  hazards?: string[];
  keyPointsOfInterest?: string[];
}

export interface UniverseFaction {
  id: string;
  name: string;
  ideology: string;
  motive: string;
  relationshipToPlayer: 'ally' | 'hostile' | 'neutral' | 'unknown';
}

export interface UniverseCharacter {
  id: string;
  name: string;
  role: string; // e.g. "Protagonist", "Rogue AI Companion", "Antagonist"
  background: string;
  abilities: string[];
  visualDescription: string;
}

export interface UniverseState {
  universeId: string;
  title: string;
  tagline: string;
  description: string;
  genre: string;
  settingTheme: string; // e.g. "Europa Sci-Fi Isolation", "Cyberpunk Synthwave"
  worldRules: string[];
  locations: UniverseLocation[];
  factions: UniverseFaction[];
  characters: UniverseCharacter[];
  physicsRules: {
    gravity: number; // e.g. 9.8 or 1.3
    atmosphereDensity: string;
    environmentalHazards: string[];
  };
  visualStyle: {
    artStyle: string; // e.g. "Retro Vector Neon", "Cinematic Dark Pixel", "Low Poly Sci-Fi"
    colorPalette: string[];
    lightingMood: string;
  };
  createdAt: string;
  updatedAt: string;
}

// Game Specification generated by Game Director & Builder Pipeline
export interface PhysicsConfig {
  gravity: number; // Y-acceleration
  friction: number;
  restitution: number; // bounciness
  jumpForce: number;
  moveSpeed: number;
  hasCollisionDetection: boolean;
  particleEffects: boolean;
}

export interface GameSpecification {
  gameId: string;
  universeId: string;
  title: string;
  version: string; // e.g. "1.0.0"
  logline: string;
  genre: string;
  subgenre: string;
  viewPerspective: '2D_SIDE_SCROLLER' | '2D_TOP_DOWN' | '2D_ISOMETRIC' | 'CANVAS_ARCADE';
  coreLoop: string;
  controls: {
    key: string;
    action: string;
  }[];
  winCondition: string;
  lossCondition: string;
  physicsConfig: PhysicsConfig;
  entities: {
    name: string;
    type: 'player' | 'enemy' | 'item' | 'obstacle' | 'goal';
    color: string;
    size: { width: number; height: number };
    behavior: string;
  }[];
  generatedCode?: string; // HTML5 Canvas standalone code executable in sandboxed iframe
}

// Game Discovery Types
export interface DiscoveredGame {
  id: string;
  title: string;
  developer: string;
  releaseYear: number;
  platforms: string[];
  genres: string[];
  coverImage?: string;
  description: string;
  matchScore: number; // 0 to 100
  matchReason: string;
  keyDifferences: string;
  playabilityUrl?: string;
}

export interface GameDiscoveryRequest {
  naturalPrompt: string;
  limit?: number;
  filterPlatforms?: string[];
}

export interface GameDiscoveryResponse {
  queryIntent: {
    extractedGenres: string[];
    extractedThemes: string[];
    desiredMechanics: string[];
    pacing: string;
  };
  recommendedGames: DiscoveredGame[];
  aiAnalysis: string;
}

// Game Versioning & Evolution Types
export interface GameVersion {
  versionId: string;
  gameId: string;
  versionNumber: string; // e.g. "1.1"
  userFeedbackPrompt?: string;
  changesApplied: string[];
  generatedCode: string;
  createdAt: string;
}

export interface PlayerFeedbackRequest {
  gameId: string;
  currentVersion: string;
  feedbackText: string; // e.g. "Make jumping higher and add atmospheric particle storm"
  desiredChanges: ('harder' | 'darker_atmosphere' | 'more_exploration' | 'faster_pacing' | 'custom')[];
}

// Server API Request / Response Wrappers
export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: unknown;
  };
  meta?: {
    processingTimeMs: number;
    phase: string;
    modelsUsed?: string[];
  };
}

export interface OrchestrateRequest {
  userPrompt: string;
  guestSessionId?: string;
  mode?: 'full_universe' | 'discovery_only' | 'quick_game';
}

export interface OrchestrateResponse {
  universeState: UniverseState;
  gameSpecification: GameSpecification;
  discoveredGames: DiscoveredGame[];
  agentExecutionLog: AgentTaskStatus[];
}

// Game Director Phase 4 Types
export interface DesignTask {
  objective: string;
  requiredInputs: string[];
  expectedOutputs: string[];
  priority: "high" | "medium" | "low";
}

export interface GameDirectorPlan {
  requestId: string;
  originalPrompt: string;
  expandedPrompt?: string;

  intent: {
    summary: string;
    genre: string[];
    theme: string[];
    setting: string;
    playerRole: string;
    cameraPerspective: string;
    gameplayStyle: string[];
    atmosphere: string[];
  };

  designDomains: {
    world: DesignTask;
    story: DesignTask;
    character: DesignTask;
    gameplay: DesignTask;
    physics: DesignTask;
    cinematography: DesignTask;
  };

  constraints: string[];
  assumptions: string[];

  pipeline: {
    stage: string;
    status: "pending" | "processing" | "complete" | "failed";
  }[];
}
